<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PUNITP395549D" name="Create Customer Account" tests="1" failures="1" timestamp="19 Sep 2017 11:46:41 GMT" time="82.173" errors="0">
  <testcase name="LoginSuccess" time="82.135" classname="pelascopy.testscripts.Generic.CustomerCreation">
    <failure type="java.lang.Exception">
      <![CDATA[java.lang.Exception
	at pelascopy.testscripts.Generic.CustomerCreation.LoginSuccess(CustomerCreation.java:96)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- LoginSuccess -->
</testsuite> <!-- Create Customer Account -->
